language: objective-c
osx_image: xcode8.2
cache:
  directories:
    - vendor/bundle
    - Carthage
before_install:
  - brew update
install:
  - brew upgrade swiftlint || brew install swiftlint
  - brew upgrade carthage || brew install carthage
  - gem install xcpretty
before_script:
  - travis_wait 120 carthage bootstrap
script:
  - swiftlint
